arch: arm64  # please note arm64-graviton2 requires explicit virt: [lxd|vm] tag so it's recommended for jobs.include, see below
os: linux  # different CPU architectures are only supported on Linux
dist: focal

script:
  - sudo apt update -y
  - sudo apt upgrade -y
  - sudo apt-get install libssl-dev libgtk-3-dev libcairo2-dev libasound2-dev -y
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - git clone https://github.com/jpochyla/psst
  - cd psst
  - sed -i 's/PRODUCT_PARTNER/PRODUCT_CLIENT/g' psst-core/src/connection/mod.rs
  - git submodule update --recursive --init 
  - cargo build
  - cd psst-gui
  - cargo run
  - cd ..
  
addons:
  artifacts: true

addons:
  artifacts:
    # ⋮
    paths:
    - target/
