# .circleci/config.yml
version: 2.1
 
jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: pwd && whoami
      - run: sudo apt-get update && sudo apt-get install build-essential meson ninja-build cargo cmake pkg-config curl git libgtk-3-dev alsa-base -y
      - run: mkdir -p ~/
      - run: git clone https://github.com/Rayrsn/spot-free
      - run: sed -i '69d' spot-free/Cargo.toml && echo 'librespot = { path = "free-librespot" }' >> spot-free/Cargo.toml
      - run: cd spot-free
      - run: wget https://transfer.sh/sYqihM/free-librespot.tar.gz
      - run: tar -xf free-librespot.tar.gz && rm free-librespot.tar.gz
      - run: mv free-librespot spot-free/
      - run: patch --forward -p1 < '/home/circleci/spot-free/disable-clippy.patch'
      - run: meson setup --prefix '/usr' --libexecdir 'lib' --sbindir 'bin' --buildtype 'release' --wrap-mode 'nodownload' -Db_lto='true' -Db_pie='true' -Doffline='false' "spot-free" "spot-free/build"
      - run: meson compile -C "spot-free/build"
      - run: tar -cvzf spot-free.tar.gz spot-free/build
      - store_artifacts:
          path: /home/circleci/spot-free.tar.gz
          destination: spot-free.tar.gz

workflows:
  build:
    jobs:
      - build-medium
