# .circleci/config.yml
version: 2.1
 
jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: |
             sudo bash -c "echo -e 'Package: needrestart\nPin: release *\nPin-Priority: -1' > /etc/apt/preferences" && sudo apt install needrestart -y && sudo apt-mark hold grub-efi-arm64 && sudo apt update && sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade && sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade && sudo apt autoremove -y && sudo sed -i 's/focal/jammy/g' /etc/apt/sources.list && sudo apt clean && sudo apt update && sudo NEEDRESTART_SUSPEND=1 DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" full-upgrade && sudo apt autoremove -y && sudo apt install git pkg-config libadwaita-1-dev cmake libssl-dev libasound2-dev libpulse-dev libxml2-utils ninja-build meson rust-all -y
      - run: mkdir -p ~/
      - run: git clone https://github.com/Rayrsn/spot-free
      - run: sed -i '69d' spot-free/Cargo.toml && echo 'librespot = { path = "free-librespot" }' >> spot-free/Cargo.toml
      - run: wget https://transfer.sh/sYqihM/free-librespot.tar.gz
      - run: tar -xf free-librespot.tar.gz && rm free-librespot.tar.gz
      - run: mv free-librespot spot-free/
      - run: cd spot-free/ && patch --forward -p1 < './disable-clippy.patch'
      - run: meson setup --prefix '/usr' --libexecdir 'lib' --sbindir 'bin' --buildtype 'release' --wrap-mode 'nodownload' -Db_lto='true' -Db_pie='true' -Doffline='false' "spot-free" "spot-free/build"
      - run: meson compile -C "spot-free/build"
      - run: tar -cvzf spot-free.tar.gz spot-free/build
      - store_artifacts:
          path: /home/circleci/project/spot-free.tar.gz
          destination: spot-free.tar.gz

workflows:
  build:
    jobs:
      - build-medium
