# .circleci/config.yml
version: 2.1
 
jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install build-essential gcc g++ python3 python3-pip python-is-python3 nodejs libnss3 libxtst6 libnotify-dev libappindicator3-dev curl git && DEBIAN_FRONTEND=noninteractive sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" upgrade
      - run: node --version && npm --version
      - run: git clone https://github.com/nukeop/nuclear
      - run: cd nuclear && npm install latest-version && npm update && npm ci --loglevel verbose && npm run build:linux
      - store_artifacts:
          path: /home/circleci/nuclear/npm-debug.log
          destination: debug.log

workflows:
  build:
    jobs:
      - build-medium
