name: nuclear-aarch64-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gnu_linux_aarch64:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Build on Ubuntu-20.04 aarch64
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.1.0
    - name: Build and install the executable
      uses: uraimo/run-on-arch-action@v2.1.1
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu20.04
        run: |
          apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install sudo build-essential gcc g++ python3 python3-pip python-is-python3 libnss3 libxtst6 libnotify-dev libappindicator3-dev curl git && DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" upgrade
          mkdir -p ~
          git clone https://github.com/nukeop/nuclear
          mv nuclear/* /home/runner/work/Aariz-Build-Env/Aariz-Build-Env/
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        version: 12.x
        cache: npm
    - run: sudo npm ci && sudo npm test && sudo npm run build:linux
      shell: bash
    - name: Tar files
      if: always()
      run: sudo tar -cvzf nuclear-aarch64.tar.gz nuclear/
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: nuclear-aarch64
        path: nuclear-aarch64.tar.gz
