name: nuclear-aarch64-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gnu_linux_aarch64:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Build on Ubuntu-20.04 aarch64
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.1.0
    - name: Build and install the executable
      uses: uraimo/run-on-arch-action@v2.1.1
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu20.04
        run: |
          apt-get update && apt-get -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-confdef" install sudo build-essential gcc g++ python3 python3-pip python-is-python3 nodejs npm libnss3 libxtst6 libnotify-dev libappindicator3-dev curl git -y && apt-get -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-confdef" upgrade -y
          npm install --global lerna
          mkdir -p ~
          git clone https://github.com/nukeop/nuclear
          cd nuclear
          if ! ls ~/.npm; then mkdir ~/.npm;fi
          if ! ls /usr/lib/node_modules; then mkdir /usr/lib/node_modules;fi
          sudo chown -R $(whoami) ~/.npm
          sudo chown -R $(whoami) /usr/lib/node_modules
          sudo npm install -g sqlite3 --unsafe-perm=true --allow-root 
          pip install git+https://chromium.googlesource.com/external/gyp
          npm install
          lerna bootstrap
          npm run build  
    - name: Tar files
      if: always()
      run: sudo tar -cvzf nuclear-aarch64.tar.gz nuclear/
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: nuclear-aarch64
        path: nuclear-aarch64.tar.gz
