name: psst-aarch64-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gnu_linux_aarch64:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Build on Ubuntu-20.04 aarch64
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.1.0
    - name: Build and install the executable
      uses: uraimo/run-on-arch-action@v2.0.5
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu20.04
        run: |
          apt-get update && apt-get install build-essential curl git libssl-dev libgtk-3-dev libcairo2-dev libasound2-dev -y
          mkdir -p ~
          git clone https://github.com/jpochyla/psst.git
          cd psst
          sed -i 's/PRODUCT_PARTNER/PRODUCT_CLIENT/g' psst-core/src/connection/mod.rs
          mkdir ~/.cargo
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          git submodule update --recursive --init
          PATH=$PATH:~/.cargo/bin cargo build --no-default-features --features pulseaudio-backend
          cd psst-gui
          PATH=$PATH:~/.cargo/bin cargo run
    - name: Tar files
      if: always()
      run: sudo tar -cvzf psst-aarch64.tar.gz psst/target/

    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: psst-aarch64
        path: psst-aarch64.tar.gz
