name: windows-aarch64-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gnu_linux_aarch64:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Build on Ubuntu-20.04 aarch64
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.1.0
    - name: Build and install the executable
      uses: uraimo/run-on-arch-action@v2.0.5
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu20.04
        run: |
          apt-get update && apt install unrar -y
          wget https://archive.org/download/windows10ARM/windows10ARM.rar
          unrar e windows10ARM.rar
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: windows-aarch64
        path: windows10arm64.qcow2
